---
title: "NBA Final project"
author: "Achraf cherkaoui"
date: "12/2/2021"
output: 
  pdf_document:
    latex_engine: xelatex
    keep_tex: yes
  html_document:
    df_print: paged
header-includes: \usepackage{color}
urlcolor: blue
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r ,eval=TRUE} 
library(ggplot2)
library(dplyr)
library(readxl)
library(car)
NBA <- read_excel("nba_teamgame_20167_orig.xlsx")
View(NBA)
```
 
 
 
```{r,eval=TRUE}
# all new orleans winning games for the whole season in game type 1 since they did not qualify to the play off. 
pl1 <- NBA %>%
  select(Team , Home , GameType , To , TeamWin)%>%
  filter(Team == "New Orleans" , TeamWin == "1") 
pl1 
p1<- nrow(pl1) 
p1
mean(pl1$To) # average of turnover in winning game in the whole season
```


```{r,eval=TRUE}
#New Orleans winning games  at home for game type 1 
pl <- NBA %>%
  select(Team , Home , GameType , To , TeamWin)%>%
  filter(Team == "New Orleans" , Home== "1" ,TeamWin == "1" ,GameType == '1') 
pl 
p<-nrow(pl)
p
mean(pl$To) # average of turnover for winning games  at home for game type 1
```

```{r,eval=TRUE} 
#New Orleans winning games  away  for game type 1 
pl2 <- NBA %>%
  select(Team , Home , GameType , To , TeamWin)%>%
  filter(Team == "New Orleans" , Home== "0" ,TeamWin == "1" ,GameType == '1') 
pl2  
p2 <- nrow(pl2)  
p2
mean(pl2$To) # average of turnover for winning games  away  for game type 1 
```




```{r,eval=TRUE}
#plot 
df <- data.frame(game = c("Home game", "Road game" , "whole season"),
                number=c(p, p2, p1))
df
ggplot(data=df, aes(game , number)) +
  geom_bar(stat="identity" , fill = "cadetblue" )+
   geom_text(aes(label=number), vjust=1.6, color="white", size=3.5)+
  theme_bw()+
  labs(title= " bar plot : number of games won in game type one") 

dff <- data.frame(game = c("Home game win", "Road game win"),
                number=c(p, p2))
dff

pie <- plotly::plot_ly(data = dff, labels = ~game, values = ~number, 
                type = 'pie', sort= FALSE,
                marker= list(colors=colors, line = list(color="black", width=1)))%>%  layout(title= 'Pie chart : new Orleans percentage games won')
pie 

```

**\color{red}{comment}** new orleanse won 34 games where 21 one games won at home and 13 won away. 

```{r,eval=TRUE}
# all new orleans lost games for the whole season in game type one 
pll1 <- NBA %>%
  select(Team , Home , GameType , To , TeamWin)%>%
  filter(Team == "New Orleans" , TeamWin == "0") 
pll1 
pl1 <-nrow(pll1) 
pl1
mean(pll1$To) #average turnover for lost games in the whole season 
```

```{r,eval=TRUE}
#New Orleans lost games  at home for game type 1 
pll <- NBA %>%
  select(Team , Home , GameType , To , TeamWin)%>%
  filter(Team == "New Orleans" , Home== "1" ,TeamWin == "0" ,GameType == '1') 
pll 
pl <-nrow(pll) 
pl
mean(pll$To) # average turnover for lost game at home for game type 1 
```

```{r,eval=TRUE}
#New Orleans lost games  away  for game type 1 
pll2 <- NBA %>%
  select(Team , Home , GameType , To , TeamWin)%>%
  filter(Team == "New Orleans" , Home== "0" ,TeamWin == "0" ,GameType == '1') 
pll2 
pl2 <- nrow(pll2)  
pl2
mean(pll2$To) 
```

```{r,eval=TRUE}
#plot 
df1 <- data.frame(game = c("Home game", "Road game" , "whole season"),
                number=c(pl, pl2, pl1))
df1
ggplot(data=df1, aes(game , number)) +
  geom_bar(stat="identity" , fill = "cadetblue" )+
   geom_text(aes(label= number), vjust=1.6, color="white", size=3.5)+
  theme_bw()+
  labs(title= " bar plot : number of games lost in game type one")

```
**\{red}{comment}** new orleanse lost 48 games,28 games away and 20 games at home 

```{r,eval=TRUE} 
df11 <- data.frame(game = c("Home game lost ", "Road game lost" ),
                number=c(pl, pl2))
df11
pie1 <- plot_ly(data = df11, labels = ~game, values = ~number, 
                type = 'pie', sort= FALSE,
                marker= list(colors=colors, line = list(color="black", width=1))) %>% layout(title="Pie chart : new orleanse percentage games lost   ")
pie1
```

```{r,eval=TRUE}
ddf <- data.frame(game = c("whole season lost", "whole season win" ),
                number=c(pl1, p1))
ddf
pie2 <- plot_ly(data = ddf, labels = ~game, values = ~number, 
                type = 'pie', sort= FALSE,
                marker= list(colors=colors, line = list(color="black", width=1))) %>%
  layout(title="Pie chart : new orleanse percentage games ")
pie2 
ggplot(data=df1, aes(game , number)) +
  geom_bar(stat="identity" , fill = "cadetblue" )+
   geom_text(aes(label=number), vjust=1.6, color="white", size=3.5)+
  theme_bw()+
  labs(title= " bar plot : number of games lost in game type one")
```

**\{red}{comment}** New Orleans played 82 games,won 34 games and lost 48 games. 


```{r,eval=TRUE} 

p <-NBA %>% 
  filter(Team == "New Orleans", Home =="1" , TeamWin=="1")

sum(p$TeamWin)
```

```{r,eval=TRUE}
meanofassiste <- NBA %>%
  select(Team , Ast)%>%
  group_by(Team)%>%
  summarise(average = mean(Ast))
meanofassiste 

meanofassisteforwinningt <- NBA %>%
  select(Team , Ast , TeamWin)%>% 
  filter(TeamWin == "1")%>%
  group_by(Team)%>%
  summarise(average = mean(Ast)) 
meanofassisteforwinningt
mean(meanofassisteforwinningt$average)
  
meanofassisteforlosingt <- NBA %>%
  select(Team , Ast , TeamWin)%>% 
  filter(TeamWin == "0")%>%
  group_by(Team)%>%
  summarise(average = mean(Ast)) 
meanofassisteforlosingt
mean(meanofassisteforlosingt$average) 



```

```{r,eval=TRUE} 
library(dplyr)
meanofdata <- NBA %>%
  group_by(Team)%>%
  summarise(avReb= mean(Reb),avdreb=mean(Dreb) ,avoreb=mean(Oreb), av1To=mean(To) , av2Ast=mean(Ast), av3st=mean(Stl), av4pf=mean(Pf) ,av5fg3m=mean(fg3m), av6fg3a= mean(fg3a),av7fg2m=mean(Fg2m),av8fg2a = mean(Fg2a))
meanofdata 

meanofdatawinning <- NBA %>%
  filter(TeamWin == "1")%>%
  group_by(Team)%>%
  summarise(avReb= mean(Reb),avdreb=mean(Dreb) ,avoreb=mean(Oreb), av1To=mean(To) , av2Ast=mean(Ast), av3st=mean(Stl), av4pf=mean(Pf) ,av5fg3m=mean(fg3m), av6fg3a= mean(fg3a),av7fg2m=mean(Fg2m),av8fg2a = mean(Fg2a))
meanofdatawinning 

meanofdatalosing <- NBA %>%
  filter(TeamWin == "0")%>%
  group_by(Team)%>%
  summarise(avReb= mean(Reb),avdreb=mean(Dreb) ,avoreb=mean(Oreb), av1To=mean(To) , av2Ast=mean(Ast), av3st=mean(Stl), av4pf=mean(Pf) ,av5fg3m=mean(fg3m), av6fg3a= mean(fg3a),av7fg2m=mean(Fg2m),av8fg2a = mean(Fg2a))
meanofdatalosing

#average rebound of winning teams vs losing teams 
mm1 <- mean(meanofdatawinning$avReb)
mm2 <- mean(meanofdatalosing$avReb)

 
```



```{r,eval=TRUE} 
a <- NBA %>%
  filter(Team == "New Orleans" , TeamWin == "1" , Home =="1" ,GameType =="1")
a  

b<- NBA %>%
  filter(Team == "New Orleans" , TeamWin == "1" )
b  

c <- NBA %>%
  filter(Team =="New Orleans") 
nrow(c)
##################################
###  whole season 
##################################
#new Orleans total rebound in the whole season 
sum(c$Reb) 
#new orleanse total offesive rebound in the whole season 
sum(c$Oreb)
#new orleans total defensive rebound in the whole season 
sum(c$Dreb) 
#total free throw attempt in the whole season 
sum(c$Fta) 
#total free throw made in the whole season
sum(c$Ftm)
#total of assist in the whole season 
sum(c$Ast)
# field goal made 
sum(c$Fgm)
#turnovers
sum(c$To)
######################################################
###  all winning games 
####################################################### 
#3 points attemp
sum(b$fg3a)
#numbre of field goal made 
sum(b$Fgm)
#turn overs 
sum(b$To)
#total of assist in the winning games season 
sum(b$Ast)
#new orleans free throw attempt in wining games
sum(b$Fta) 
#new orleans free throw made in wining games
sum(b$Ftm)
#new orleans total rebounds in all  winning games 
awgr <- sum(b$Reb)
awgr 
#new orleans total offensive rebounds in all  winning games  
awor <- sum(b$Oreb) 
#percentage of offensive rebounds in all winning games 
porwg <- (awor/awgr)*100
porwg

#new orleans total defensive rebounds in all  winning games
awdr<- sum(b$Dreb)
#percentage of defensive rebound in all winning games 
podrwg <- (awdr/awgr)*100
podrwg

########################################################
##       HOME winning games
######################################################## 
#number of field goals made home winning games 
sum(a$Fgm)
#turnovrrs 
sum(a$To)
#total of assist in the home winning games 
sum(a$Ast)
#new orleans total free thrrw attempt in  home game
sum(a$Fta)
# 3 points attempt 
sum(a$fg3a)
#new orleans total free throw made in  home game
sum(a$Ftm)

#new orleans total rebounds in all home winning games
nws <-sum(a$Reb)

#new orleans total offensive rebound in all home winning games 
nwsowh <- sum(a$Oreb)
nwsowh 
#new orleans percentage of all offensive rebounds in home winning games 
nwp <- (nwsowh/nws)*100
nwp
#mew orlens defensive rebound in all home winnig games 
nwd<- sum(a$Dreb) 
#new Orleans percentage of defensive rebound in home winning games 
nsdp <- (nwd/nws)*100 
nsdp 


####################  
##alllosing games
####################
 
d<- NBA %>%
  filter(Team == "New Orleans" , TeamWin == "0" )
#new Orleans total rebound in all losing games 
trlg <- sum(d$Reb)
#new orleans total offensive rebound in 

#new oreanse total offencive rebound in all losing games 
orlg <- sum(d$Oreb)

# percentage of offensive rebound in all losing games 
porlg <- (orlg/trlg)*100
porlg 
#3ppint 
sum(d$fg3a)
#free throw attemtpt in losing games 
sum(d$Fta) 
#new orleans total free throw made in losing games 
sum(d$Ftm)
#total of assist in the losing games season 
sum(d$Ast) 
#number of field gold made in losing games 
sum(d$Fgm)
#turnovers
sum(d$To)

#############################
### away
#############################

e<- NBA %>%
  filter(Team == "New Orleans" , TeamWin == "0" , Home=="0" ) 
#mew orleans total rebound in losing game at home 
sum(e$Reb) 
#new oleans total offensive rebound in home losins games
sum(e$Oreb)

#free throw attemtpt in losing games home
sum(e$Fta)
#free throw made in losing games home
sum(e$Ftm)
#total of assist in the losing games away
sum(e$Ast)
# field goal made losnig away 
sum(e$Fgm)
#turnovers
sum(e$To)
``` 

```{r,eval=True}  
#rebound bar plot   
###################################################################
rebdatafram <- data.frame( supp=rep(c("winnig games offensive reboubs", "winnig games defensive reboubs" ,"losining games offensive reboubs " , "losing games defensive reboubs ")), each=2 ,rebound = c("home win OFR","home win DFR" ,"away win OFR" ,"away win DFR" , "home lose OFR","home lose DFR" ,"away lose OFR" ,"away lose DFR"  ),
                number=c(173,822, 124,468,191,675,223,912))

g <- ggplot(data=rebdatafram, aes(x=rebound, y=number, fill= supp)) +
geom_bar(stat="identity", position=position_dodge())+theme_bw()+
  labs(title= " Bar plot : New Orleans offensive and defensive rebound for the regular season")+geom_text(aes(label=number), vjust=1.6, color="white",
            position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired") 
library(plotly)
plot_ly(data = rebdatafram, labels = ~rebound, values = ~number, 
                type = 'pie', sort= FALSE,
                marker= list(colors=colors, line = list(color="black", width=1)))
 

library(GGally)
n<-NBA[,-1]
b<-n[,-1]
a<-b[,-1]
nba<-a[,-1]
View(nba)
ggpairs(nba)
```

```{r,eval=TRUE}
# z test for new orleans winning games away and at home. 
prop.test(x=c(21,13) , n=c(34,34) , alternative = "greater") 

# it is statistically significant that new orleans win more games than awat meaning that they play well at home then away 

# z test for new orleans losing games away and at home. 
prop.test(x=c(20,28) , n=c(48,48) , alternative = "less")

# in contrast of winning games . there is no significant in losing games away or at home for new orleans 

```

```{r,eval=TRUE}
team <- NBA%>%
  arrange(Team , Opponent )
oppon <- NBA %>%
  arrange(Opponent , Team) 
nn <- data.frame( team , oppon)   
nh1 <- nn %>%
  filter(Home == "1")

nna <- nh1[,c(-1,-2,-3,-4,-11,-29,-30,-31,-32,-33,-34,-35,-36,-37,-38,-39 )] 
#NBA$Home <- as.factor(NBA$Home)
#NBA$GameType <- as.factor(NBA$GameType)
#NBA$TeamWin <- as.factor(NBA$TeamWin)
NBA$Min <- as.factor(NBA$Min)
percentage <- nna %>%
  dplyr::summarise(percentagefor3piont = fg3m / fg3a , pecentagefor2point = Fg2m/Fg2a , percentagrforoppnent3point= fg3m.1/fg3a ,percentagrforoppnent2point= Fg2m.1/Fg2a , percentafreethrow = Ftm/Fta , opponentfreethrowpercentage=Ftm.1/Fta.1 )
  
data<- data.frame(nna,percentage)  
data1 <-data[,c(-1,-2,-4,-7,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,-32,-33,-34,-35,-36,-37,-38,-39,-40)]
View(data1) 

#data1$Home <- as.character(data1$Home)
data1$GameType <- as.factor(data1$GameType)
data1$Min <- as.factor(data1$Min)
str(data1) 
str(data1)

mlr<- lm(data =data1 , TeamScr~ .  )
summary(mlr) 
vif(mlr)
 

#forward selection
start <- lm(TeamScr~1 , data=data1)
end <- lm(TeamScr~. ,data = data1)
step.model <- step(start, direction = "forward" , scope = formula(end))
summary(step.model)
AIC(step.model)
BIC(step.model)
#stepwise
bothstep.model <- step(start, direction = "both" , scope = formula(end))
summary(bothstep.model)

vif(step.model)


#predict the team score for golden state 
newdata <- data.frame(Ast=24, pecentagefor2point = 33/52 ,percentagefor3piont = 7/33 ,Pf.1=19  ,Oreb =8 ,  Dreb.1=34 , percentafreethrow=13/18 , To =16 , Min = 48 , Blk.1 = 3, 
    Dreb = 27, Ast.1 =25 , Stl=11 , Pf = 19 , opponentfreethrowpercentage  =23/26 ,percentagrforoppnent2point = 35/74, 
    percentagrforoppnent3point = 12/24, To.1 = 13, Blk =6 ,  Stl.1 =13  ) 

predict( step.model , newdata)

# prediction or new orleanse score for all games 
periction <- data.frame(nn , percentage) %>%
  filter( Team == "New Orleans")
periction$Min <-as.factor(periction$Min)
p <- predict(step.model , periction) 

pm <- data.frame(p ,periction)  

# prediction score for golden state 
golden <- data.frame(nn , percentage )%>% 
 filter( Team == "Golden State", GameType == "2"  , Opponent == "Cleveland") 
golden$Min <- as.factor(golden$Min)
pgolden <- predict(step.model , golden)  
pgolden 

# prediction score for cleveland
cleveland <- data.frame(nn , percentage )%>% 
 filter( Team == "Cleveland", GameType == "2"  , Opponent == "Golden State") 
cleveland$Min <- as.factor(cleveland$Min)
pcleveland<- predict(step.model , cleveland)  
pcleveland

#teams improvement golden state 
teamsimprovemnt<- data.frame(nn , percentage )%>% 
 filter( Team == "Golden State" , GameType =="1" )
teamsimprovemnt1<- data.frame(nn , percentage )%>% 
 filter( Team == "Golden State" , GameType =="2" )
tg <-mean(teamsimprovemnt$To)
tg1 <-mean(teamsimprovemnt1$To) 
drp <- (sum(teamsimprovemnt$Dreb)/sum(teamsimprovemnt$Reb)) 
drp1 <-(sum(teamsimprovemnt1$Dreb)/sum(teamsimprovemnt1$Reb))
# t-test to know if the result is significant 
t.test(tg,tg1)


#team improvement cleveland
teamsimprovemntcl<- data.frame(nn , percentage )%>% 
 filter( Team == "Cleveland" , GameType =="1" )
teamsimprovemntcl1<- data.frame(nn , percentage )%>% 
 filter( Team == "Cleveland" , GameType =="2" )
tgcl <-mean(teamsimprovemntcl$To)
tgcl1 <-mean(teamsimprovemntcl1$To) 
drpcl <- (sum(teamsimprovemntcl$Dreb)/sum(teamsimprovemntcl$Reb)) 
drpcl1 <-(sum(teamsimprovemntcl1$Dreb)/sum(teamsimprovemntcl1$Reb))
# t-test to know if the result is significant 
t.test(tgcl,tgcl1)
```

